# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SampleAppleSignIn' do
  use_frameworks!
  pod 'Firebase/Auth'
  pod 'CoreUI', :git => "https://github.com/y4gamilight/swift-core-ui.git", :tag => "1.0.0" 

end

# Workaround for Cocoapods issue #7606
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
